services:
  - type: web
    name: one-step-app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: one-step-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: one-step-db
    plan: free